import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { Header } from "@/components/Header";
import { MobileNav } from "@/components/MobileNav";
import { SidebarProfile } from "@/components/SidebarProfile";
import { NavList } from "@/components/NavList";
import { MessagesList } from "@/components/MessagesList";
import { LikesList } from "@/components/LikesList";
import { Toaster } from "@/components/ui/sonner";
import { MiniKitProvider } from "@worldcoin/minikit-js/minikit-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <MiniKitProvider>
        <head>
          <Script id="theme-no-flash" strategy="beforeInteractive">{`
            (function(){
              try {
                var stored = localStorage.getItem('theme');
                var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                var useDark = stored ? stored === 'dark' : prefersDark;
                var root = document.documentElement;
                if (useDark) root.classList.add('dark'); else root.classList.remove('dark');
                root.setAttribute('data-theme', useDark ? 'dark' : 'light');
              } catch (e) {}
            })();
          `}</Script>
        </head>
        <body className="antialiased">
          <ErrorReporter />
          <Script
            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
            strategy="afterInteractive"
            data-target-origin="*"
            data-message-type="ROUTE_CHANGE"
            data-include-search-params="true"
            data-only-in-iframe="true"
            data-debug="true"
            data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
          />
          <Header />
          <div className="min-h-svh bg-[var(--background)] text-[var(--foreground)]">
            <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-6 grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)_320px]">
              {/* Left Sidebar - hidden on mobile */}
              <aside className="space-y-6 lg:sticky lg:top-16 self-start hidden lg:block">
                <SidebarProfile />
                <NavList />
              </aside>

              {/* Center Content */}
              <section className="space-y-6">{children}</section>

              {/* Right Sidebar - hidden on mobile */}
              <aside className="space-y-6 lg:sticky lg:top-16 self-start hidden lg:block">
                <MessagesList />
                <LikesList />
              </aside>
            </main>
          </div>

          {/* Mobile Navigation - visible only on small screens */}
          <MobileNav />

          <VisualEditsMessenger />
          <Toaster position="top-right" richColors />
        </body>
      </MiniKitProvider>
    </html>
  );
}
